services:
  app:
    build: .
    restart: always
    container_name: fastapi_app
    ports:
      - "8000:8000"

  db:
    container_name: sqlite_db
    volumes:
      - db_data:/data

volumes:
  db_data: